version: "3.4"

services:
    frrsp:
      image: frrsp
      volumes:
        - "./cert.pem:/etc/raddb/cert.pem"
        - "./key.pem:/etc/raddb/key.pem"
      ports:
        - 1812/udp
        - 1813/udp
